services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./volumes/conf:/etc/caddy
      - ./volumes/site:/srv
      - ./volumes/data:/data
      - ./volumes/config:/config