- name: Update Debian/Ubuntu LXCs
  hosts: debian_servers
  gather_facts: false
  tasks:
    - name: Update apt cache and upgrade packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
      register: apt_result
      changed_when: apt_result.changed